### ISSUE TITLE
2017 todo

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/annual-report#42]
Annual report todo

### General

- [x] Repeat navigation in footer (makes mobile use much easier)
- [x] Add final stats 
- [x] Add final quotes
- [x] Check all stats for overflow (once final stats are added)
- [x] Check OG tags and images
- [x] Recompress all images
- [ ] Check SVG failover
- [x] Add donate button to header
- [x] Add 'next up' navigation to bottom of each page
- [x] Beef up the donate call to action on the help page
- [x] Better fallback CSS styling for Twitter blockquotes, for if/when Twitter JS is blocked
- [ ] Cross browser (just check and fix any disasters)

### Homepage

- [x] Make the 'mission' nicer
- [x] Finish the 'section' links
- [x] 'One word or phrase' section needs design

### In figures

- [x] Header (make more specific somehow)
- [x] Section up to make all the numbers a bit clearer
- [x] 'Places we've worked' needs designing
- [x] TicTec section needs designing
- [x] 'Fond farewells' needs something

### FOI

- [x] Header (make more specific somehow)
- [x] WDTKpro quotes
- [x] Tenth birthday (add illustration)
- [x] OPRA Machine needs design
- [x] 'Number of requests' section
- [x] Link up stories

### Better cities

- [ ] Header (make more specific somehow)
- [x] Bot illustration
- [x] Birthday illustration
- [x] Tweets need some design
- [x] "that went into *into* Alex’s paper" typo

### Democracy

- [x] Header (make more specific somehow)
- [x] Needs more defined sections
- [x] Pombola sites graphic
- [x] Embedded YouTube video isn’t responsive (try the page at 320px width)
- [x] girl guides badges
- [x] world map graphic @zarino

### How you help

- [x] Header (make more specific somehow)
- [x] Some design
- [x] More visual interest for "fantastic funders" section (maybe icons for each list item, like we did for the FOI requests / news stories on the FOI page?)
- [x] "Loyal donors" and "Visitors like you" sections look a bit lost on wide screens
- [x] Heading into 2018

**Comment by MyfanwyNixon** [comment]
- [ ] https://2017.mysociety.org/credits/ needs updating (don't think you have this listed?)

**Comment by MyfanwyNixon** [comment]
- [ ] https://2017.mysociety.org/credits/ needs updating (don't think you have this listed?)
- [ ] really sorry but I think we'll have to lose 'WhatDoTheyKnow turned ten' since we're going to celebrate this in February.

**Comment by MyfanwyNixon** [comment]
Here's a mixture of parts that have been updated since you imported the copy, and new thoughts that have occurred to me having seen the copy in situ. Sorry for all the last-minute snagging! 

There are some more figures to follow, and I should probably pass over the latest version of the copy document one more time to make sure nothing else has been updated that I haven't picked up on.

**Homepage**:

>This year we’ve extended our services to also help those who, in the course of their work, hold power to account or open up channels of citizen communication, to the benefit of us all. 

Can we emphasise 'in the course of their work' either with bold or italic or colour? Otherwise I feel like this subtle point might be missed.

**In figures:**
- Here's blurb for the Code Commits figure:
>Code is committed when a new feature or a fix is ready to go live. So that's [xxx] little bits of progress.

- Partners worked with is 38
- Link 'ASL19 working in Iran' to https://www.mysociety.org/2017/01/18/how-secrecy-helped-us-bring-about-transparency/ and 'Open Culture Foundation in Taiwan' to https://www.mysociety.org/2017/10/02/highlights-from-tictectaipei/

>our slick new Research repository

Needs a link to http://research.mysociety.org/

> IN #PETS

On reflection people might not know what this means so maybe 'in the Slack 'pets' channel' might help a little?

>Taipei,Taiwan

Needs a space after the comma

- Link 'Florence, Italy' to http://tictec.mysociety.org/2017
and 'Taipei, Taiwan' to http://tictec.mysociety.org/taipei

**FOI**
- Quotes from happy journos can be these tweets:
>i have moved my FOI life onto @whatdotheyknow's new pro platform, and omg it is a joy

https://twitter.com/halhod/status/913732483803488256

>Loving the new @whatdotheyknow Pro account. Super slick.

https://twitter.com/Charlie_Mole/status/881824926738644992

And Mark's comment:
https://twitter.com/markcridge/status/937989579369598977 

- OPRAMachine blog post 
Text: Unusually for an Alaveteli site, OPRAmachine covers a state rather than a country. [There’s a good reason for that](https://www.mysociety.org/2017/12/06/introducing-opramachine-tackling-political-corruption-in-new-jersey/ ).

**Better Cities**

> Installed and deployed worldwide, see them here. 

Replace comma with a dash

>MapIt blurb

Change to 'Our geographic points-to-boundaries API helps power a lot of projects across the web'

>Number of FixMyStreet reports of dog mess that went into into Alex’s paper

Reword to avoid awkward repeat of 'of':
> 'Number of FixMyStreet reports about dog mess that went into into Alex’s paper'

- [Juicy?! Assume Alex's quote is replacing that :) “One of the "interesting" side effects of FixMyStreet is a database of places people have reported dog poop (or "dog fouling" as it tends to be called academically). We now have over 20,000 locations across the UK where nature's call has both been heard, and reported.”]

**Democracy page**

- Let's put a bit of text under the EP stat so it fits in with all the others:
> "Names, positions, dates, Twitter handles, you name it"

> Emails sent to people who have subscribed to their MP or a keyword on TheyWorkforYou

add 'every month' after 'emails sent' and capitalise the 'f' in TWFY; the figure is '_over 150,000_'

- 'Projects which have used EP data' - we don't know, so change to
>## 233
>Countries EveryPolitician holds data on. We’re still missing 12.

- 'Going Pro' and 'Working with Wikidata' text has changed:
>Our vision of a ‘Democratic Commons’ — where shared data benefits all — came neatly home to roost with Facebook’s drive to connect users with their representatives.

>In the UK, Kenya, France, Germany, Japan and Argentina, the day after their general elections while a tide of democratic engagement was still riding high, [Facebook users were invited to follow the people who represent them](https://www.mysociety.org/2017/06/09/increasing-political-engagement-with-facebook/). We were also able to use the information for our own project EveryPolitician.

>## Working with Wikidata
>EveryPolitician worked closely with the Wikidata community this year — that’s where Lucy and Luca came in. Since both EveryPolitician and Wikidata aspire to provide accurate, structured data that developers can use, it’s a great partnership.

> ## Feeling the GLOW
> We supported Wikidata workshops in Bulgaria, Croatia, Greece, Italy, Nepal, Slovenia, Spain and Sweden for Global Legislative Openness Week — and mySociety folk attended as many as possible to lend a helping hand. Tony gets a special shout-out for managing to visit workshops in 5 countries in just 8 days.

https://twitter.com/okfn_np/status/936515529782697985 

> GLOW is just one part of the picture, though: over the year we’ve worked with the Wikidata community to also ensure rich political data is available for the UK, Scotland, Northern Ireland, Wales, Ireland, Australia, Pakistan, Germany, Estonia, France and the Netherlands and built new tools to make maintaining and adding that data quicker and easier.

- A snap election
tweets if you need them; select from:
https://twitter.com/retrochbabe/status/870253971423801345
https://twitter.com/annmwinter/status/871653632655151105 
https://twitter.com/PatrickMcArdle8/status/870377531777613826
https://twitter.com/MrAndyStorey/status/870204317445369856 

**Thank you page**
- Sponsorship for TICTeC - maybe highlight this/box it or something?

- Biggest/smallest/most common - maybe need a title over the top like 'donation amounts'

- The very end - I wonder if we should finish on a note like 'See you in 2018'?

**Comment by JenMysoc** [comment]
@MyfanwyNixon what about # visitors across our PMO sites in Africa? I can do that in the past year, that = 1180902 from Dec 16 to Dec 17

**Comment by MyfanwyNixon** [comment]
@jen that's good! Thanks.

**Comment by MyfanwyNixon** [comment]
Gemma says
> 73217 requests on WDTK in 2017

**Comment by lizconlan** [comment]
> 73217

The caveat is that without looking more closely that might not be 73217 **public** requests

**Comment by MyfanwyNixon** [comment]
and
>96,454 for all Alavetelis

**Comment by wrightmartin** [comment]
### IE11
- [ ] Screenshot with SVG frames doesn't work
